import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const API_BASE = process.env.REACT_APP_API_URL || 'http://localhost:5005';

const INDUSTRIES = [
  'Agriculture', 'Education', 'Finance & Banking', 'Healthcare',
  'Hospitality & Tourism', 'Logistics & Transport', 'Manufacturing',
  'NGO / Non-Profit', 'Real Estate', 'Retail & E-commerce',
  'Technology', 'Telecommunications', 'Other',
];

const BUDGETS = [
  'Under UGX 1,000,000',
  'UGX 1,000,000 – 5,000,000',
  'UGX 5,000,000 – 20,000,000',
  'UGX 20,000,000+',
  'Not sure yet',
];

const TIMELINES = [
  'ASAP – within 1 month',
  '1–3 months',
  '3–6 months',
  '6+ months',
  'Just exploring',
];

const TECH_LEVELS = [
  'Non-technical — no IT background',
  'Basic — use spreadsheets, email, standard apps',
  'Moderate — comfortable with software and cloud tools',
  'Technical — have developers or IT staff',
];

// ── Markdown-style renderer for the brief ────────────────────────────────────
function renderBrief(text) {
  if (!text) return null;
  return text.split('\n').map((line, i) => {
    if (line.startsWith('## ')) {
      return <h3 key={i} className="brief-section-title">{line.slice(3)}</h3>;
    }
    if (line.startsWith('# ')) {
      return <h2 key={i} className="brief-main-title">{line.slice(2)}</h2>;
    }
    if (line.startsWith('- ') || line.startsWith('• ')) {
      return <li key={i} className="brief-list-item">{line.slice(2)}</li>;
    }
    if (line.trim() === '') {
      return <br key={i} />;
    }
    // Bold text
    const parts = line.split(/(\*\*[^*]+\*\*)/g).map((p, j) =>
      p.startsWith('**') && p.endsWith('**')
        ? <strong key={j}>{p.slice(2, -2)}</strong>
        : p
    );
    return <p key={i} className="brief-paragraph">{parts}</p>;
  });
}

// ── Step indicators ───────────────────────────────────────────────────────────
function StepIndicator({ current, total }) {
  return (
    <div className="pbg-steps">
      {Array.from({ length: total }).map((_, i) => (
        <div
          key={i}
          className={`pbg-step-dot ${i + 1 < current ? 'done' : ''} ${i + 1 === current ? 'active' : ''}`}
        />
      ))}
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────
export default function ProjectBriefGenerator() {
  const [step, setStep]       = useState(1);
  const [loading, setLoading] = useState(false);
  const [brief, setBrief]     = useState(null);
  const [error, setError]     = useState('');
  const [copied, setCopied]   = useState(false);

  const [form, setForm] = useState({
    companyName: '',
    industry: '',
    problem: '',
    budget: '',
    timeline: '',
    techLevel: '',
    contactEmail: '',
  });

  const set = (field) => (e) => setForm(f => ({ ...f, [field]: e.target.value }));

  const canAdvance = () => {
    if (step === 1) return form.companyName.trim() && form.industry;
    if (step === 2) return form.problem.trim().length >= 20;
    if (step === 3) return form.budget && form.timeline && form.techLevel;
    return true;
  };

  const handleGenerate = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch(`${API_BASE}/api/ai/brief`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error || 'Generation failed');
      setBrief(data.brief);
      setStep(5); // Result step
    } catch (err) {
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(brief || '');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html><head><title>Project Brief — ${form.companyName}</title>
      <style>
        body { font-family: Georgia, serif; max-width: 760px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; line-height: 1.7; }
        h1 { color: #1c265e; border-bottom: 2px solid #1c265e; padding-bottom: 10px; }
        h2 { color: #1c265e; margin-top: 32px; }
        h3 { color: #334; margin-top: 24px; }
        li { margin-bottom: 6px; }
        .meta { color: #666; font-size: 0.9rem; margin-bottom: 32px; }
        .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd; color: #666; font-size: 0.85rem; }
      </style></head><body>
      <h1>Project Brief</h1>
      <div class="meta">
        <strong>${form.companyName}</strong> · ${form.industry}<br/>
        Generated by Junior Reactive AI · ${new Date().toLocaleDateString()}
      </div>
      <div>${brief.replace(/\n/g, '<br/>').replace(/## /g, '<h2>').replace(/# /g, '<h1>')}</div>
      <div class="footer">
        Generated by Junior Reactive · juniorreactive@gmail.com · +256 764 524 816<br/>
        This brief is AI-generated and serves as a starting point. Contact us for a detailed proposal.
      </div>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleReset = () => {
    setStep(1);
    setBrief(null);
    setError('');
    setForm({ companyName: '', industry: '', problem: '', budget: '', timeline: '', techLevel: '', contactEmail: '' });
  };

  // ── Step 1: Company basics ───────────────────────────────────────────────
  const renderStep1 = () => (
    <div className="pbg-step-content">
      <h3 className="pbg-step-title">Tell us about your company</h3>
      <p className="pbg-step-desc">We'll use this to tailor the brief to your context.</p>

      <div className="form-group">
        <label htmlFor="pbg-company">Company / Organisation Name *</label>
        <input
          id="pbg-company"
          type="text"
          placeholder="e.g. Kampala Logistics Ltd"
          value={form.companyName}
          onChange={set('companyName')}
        />
      </div>

      <div className="form-group">
        <label htmlFor="pbg-industry">Industry / Sector *</label>
        <select id="pbg-industry" value={form.industry} onChange={set('industry')}>
          <option value="">Select your industry…</option>
          {INDUSTRIES.map(i => <option key={i} value={i}>{i}</option>)}
        </select>
      </div>

      <div className="form-group">
        <label htmlFor="pbg-email">Contact Email (optional)</label>
        <input
          id="pbg-email"
          type="email"
          placeholder="your@email.com"
          value={form.contactEmail}
          onChange={set('contactEmail')}
        />
        <small>We'll optionally follow up with the full proposal.</small>
      </div>
    </div>
  );

  // ── Step 2: Problem description ──────────────────────────────────────────
  const renderStep2 = () => (
    <div className="pbg-step-content">
      <h3 className="pbg-step-title">Describe your challenge</h3>
      <p className="pbg-step-desc">Be as specific as possible — the more detail, the better the brief.</p>

      <div className="form-group">
        <label htmlFor="pbg-problem">
          What problem are you trying to solve? *
          <span className="pbg-char-count">{form.problem.length} / 600</span>
        </label>
        <textarea
          id="pbg-problem"
          placeholder="e.g. We currently process delivery orders manually via WhatsApp messages. Our dispatcher spends 3 hours a day copying information into spreadsheets, which leads to errors and missed deliveries. We want to automate this but don't know where to start."
          rows={6}
          value={form.problem}
          onChange={set('problem')}
          maxLength={600}
          style={{ resize: 'vertical', minHeight: 120 }}
        />
        {form.problem.length < 20 && form.problem.length > 0 && (
          <small className="pbg-hint">Please describe your problem in a bit more detail (at least 20 characters).</small>
        )}
      </div>
    </div>
  );

  // ── Step 3: Budget & timeline ────────────────────────────────────────────
  const renderStep3 = () => (
    <div className="pbg-step-content">
      <h3 className="pbg-step-title">Budget, timeline & tech level</h3>
      <p className="pbg-step-desc">This helps us give realistic recommendations.</p>

      <div className="form-group">
        <label>Approximate Budget *</label>
        <div className="pbg-radio-group">
          {BUDGETS.map(b => (
            <label key={b} className={`pbg-radio-item ${form.budget === b ? 'selected' : ''}`}>
              <input type="radio" name="budget" value={b} checked={form.budget === b} onChange={set('budget')} />
              {b}
            </label>
          ))}
        </div>
      </div>

      <div className="form-group">
        <label>Desired Timeline *</label>
        <div className="pbg-radio-group">
          {TIMELINES.map(t => (
            <label key={t} className={`pbg-radio-item ${form.timeline === t ? 'selected' : ''}`}>
              <input type="radio" name="timeline" value={t} checked={form.timeline === t} onChange={set('timeline')} />
              {t}
            </label>
          ))}
        </div>
      </div>

      <div className="form-group">
        <label>Your Team's Technical Level *</label>
        <div className="pbg-radio-group">
          {TECH_LEVELS.map(t => (
            <label key={t} className={`pbg-radio-item ${form.techLevel === t ? 'selected' : ''}`}>
              <input type="radio" name="tech" value={t} checked={form.techLevel === t} onChange={set('techLevel')} />
              {t}
            </label>
          ))}
        </div>
      </div>
    </div>
  );

  // ── Step 4: Review & generate ────────────────────────────────────────────
  const renderStep4 = () => (
    <div className="pbg-step-content">
      <h3 className="pbg-step-title">Review & Generate Brief</h3>
      <p className="pbg-step-desc">Here's what we'll use to create your brief. Edit any step before generating.</p>

      <div className="pbg-review-grid">
        <div className="pbg-review-item">
          <span className="pbg-review-label">Company</span>
          <span className="pbg-review-value">{form.companyName}</span>
        </div>
        <div className="pbg-review-item">
          <span className="pbg-review-label">Industry</span>
          <span className="pbg-review-value">{form.industry}</span>
        </div>
        <div className="pbg-review-item pbg-review-full">
          <span className="pbg-review-label">Problem</span>
          <span className="pbg-review-value">{form.problem}</span>
        </div>
        <div className="pbg-review-item">
          <span className="pbg-review-label">Budget</span>
          <span className="pbg-review-value">{form.budget}</span>
        </div>
        <div className="pbg-review-item">
          <span className="pbg-review-label">Timeline</span>
          <span className="pbg-review-value">{form.timeline}</span>
        </div>
        <div className="pbg-review-item pbg-review-full">
          <span className="pbg-review-label">Technical Level</span>
          <span className="pbg-review-value">{form.techLevel}</span>
        </div>
      </div>

      {error && (
        <div className="alert alert-error" style={{ marginBottom: 16 }}>
          ⚠️ {error}
        </div>
      )}

      <button
        className="btn btn-full-width pbg-generate-btn"
        onClick={handleGenerate}
        disabled={loading}
      >
        {loading ? (
          <span className="pbg-loading">
            <span className="pbg-spinner" />
            Generating your brief… (~15 seconds)
          </span>
        ) : (
          '✨ Generate My Project Brief'
        )}
      </button>

      {loading && (
        <p className="pbg-loading-note">
          Our AI is analysing your challenge and crafting a tailored brief. Hang tight!
        </p>
      )}
    </div>
  );

  // ── Step 5: Result ───────────────────────────────────────────────────────
  const renderResult = () => (
    <div className="pbg-result">
      <div className="pbg-result-header">
        <div className="pbg-result-meta">
          <span className="pbg-result-badge">✅ AI Brief Generated</span>
          <h3>{form.companyName} — Project Brief</h3>
          <p>Generated by Junior Reactive AI · {new Date().toLocaleDateString()}</p>
        </div>
        <div className="pbg-result-actions">
          <button className="btn btn-outline pbg-action-btn" onClick={handleCopy}>
            {copied ? '✓ Copied!' : '📋 Copy'}
          </button>
          <button className="btn btn-outline pbg-action-btn" onClick={handlePrint}>
            🖨️ Print / Save PDF
          </button>
        </div>
      </div>

      <div className="pbg-brief-content">
        {renderBrief(brief)}
      </div>

      <div className="pbg-result-cta">
        <h4>Ready to move forward?</h4>
        <p>This brief is a starting point. Contact us and we'll turn it into a full proposal — for free.</p>
        <div className="pbg-result-cta-btns">
          <Link
            to={`/apply?brief=${encodeURIComponent(form.companyName)}`}
            className="btn"
          >
            Apply for This Project →
          </Link>
          <Link to="/contact" className="btn btn-outline">
            Discuss with the Team
          </Link>
        </div>
        <button className="sr-restart-btn" onClick={handleReset} style={{ marginTop: 16 }}>
          ↩ Generate Another Brief
        </button>
      </div>
    </div>
  );

  return (
    <div className="pbg-container">
      {step < 5 && <StepIndicator current={step} total={4} />}

      {step === 1 && renderStep1()}
      {step === 2 && renderStep2()}
      {step === 3 && renderStep3()}
      {step === 4 && renderStep4()}
      {step === 5 && renderResult()}

      {step < 5 && (
        <div className="pbg-footer-nav">
          {step > 1 && (
            <button className="sr-back-btn" onClick={() => setStep(s => s - 1)}>
              ← Back
            </button>
          )}
          {step < 4 && (
            <button
              className={`btn ${!canAdvance() ? 'disabled' : ''}`}
              onClick={() => setStep(s => s + 1)}
              disabled={!canAdvance()}
            >
              Continue →
            </button>
          )}
        </div>
      )}
    </div>
  );
}
